[project]
name = "dnembedding-master"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "gensim==4.3.3",
    "networkx>=3.5",
    "nltk>=3.9.1",
    "pandas>=2.3.0",
    "scikit-learn>=1.7.0",
]
